name: Backend CI

on:
  push:
    branches: ["**"]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: ./mvnw -B package -DskipTests

      - name: Test with Maven
        run: ./mvnw -B test

      - name: Generate JaCoCo Report
        run: ./mvnw -B jacoco:report

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: backend/target/site/jacoco/
          retention-days: 5

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw

  coverage-comment:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - name: Download JaCoCo coverage report
        uses: actions/download-artifact@v4
        with:
          name: jacoco-report
          path: jacoco-report

      - name: Parse JaCoCo report
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.12.0
        with:
          jacoco-csv-file: jacoco-report/jacoco.csv
          generate-coverage-badge: true
          generate-branches-badge: true

      - name: Create coverage comment
        uses: marocchino/sticky-pull-request-comment@v2.5.0
        with:
          header: backend-pr-coverage
          message: |
            ## Backend Test Coverage Report (PR Check)

            Overall coverage: ${{ steps.jacoco.outputs.coverage }}%

            | Package | Class | Method | Line |
            |---------|-------|--------|------|
            | ${{ steps.jacoco.outputs.branches }}% | ${{ steps.jacoco.outputs.classes }}% | ${{ steps.jacoco.outputs.methods }}% | ${{ steps.jacoco.outputs.lines }}% |

            [Click here to see the full report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
