name: Build and Deploy CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "ca-central-1"
  CDK_APP_PATH: "./cdk"

permissions:
  id-token: write # Required for requesting the JWT
  contents: read # Required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/memesapp:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cdk dependencies
        run: npm install --frozen-lockfile
        working-directory: ${{ env.CDK_APP_PATH }}

      - name: Run backend tests
        run: npm run test
        working-directory: ${{ env.CDK_APP_PATH }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ACTIONS_ROLE_GITHUB }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Bootstrap and deploy CDK app
        run: cdk bootstrap && cdk deploy MemesAppStack --require-approval never
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
        working-directory: ${{ env.CDK_APP_PATH }}
