name: Combined CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw -B package -DskipTests

      - name: Test with Maven
        run: ./mvnw -B test

      - name: Generate JaCoCo Report
        run: ./mvnw -B jacoco:report

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: backend/target/site/jacoco/
          retention-days: 5

      - name: Parse JaCoCo report
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.12.0
        with:
          jacoco-csv-file: backend/target/site/jacoco/jacoco.csv
          generate-coverage-badge: true
          generate-branches-badge: true

      - name: Create coverage comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2.5.0
        with:
          header: backend-main-coverage
          message: |
            ## Backend Test Coverage (Main): ${{ steps.jacoco.outputs.coverage }}%

            | Package | Class | Method | Line |
            |---------|-------|--------|------|
            | ${{ steps.jacoco.outputs.branches }}% | ${{ steps.jacoco.outputs.classes }}% | ${{ steps.jacoco.outputs.methods }}% | ${{ steps.jacoco.outputs.lines }}% |

            [Full report in workflow artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --configuration production

      - name: Test
        run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage
          retention-days: 5

      - name: Create coverage comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2.5.0
        with:
          header: frontend-main-coverage
          message: |
            ## Frontend Test Coverage Report (Main)

            [Full report in workflow artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
